### ISSUE TITLE
[Feature] 增加标签批量写入功能，写入操作完成后停留在当前页面

### ISSUE THREAD

**Issue by xuexiaokang** [shc0743/MyPN532#4]
发现每个操作结束都会自动跳回首页，这个有点麻烦，批量格式化卡片的时候，每操作一张卡片就被返回首页，能否修改一下

**Comment by shc0743** [comment]
好的，稍后有时间会加一个批量处理功能

**Comment by shc0743** [comment]
批量处理功能已在开发，但由于作者事务繁多，预计将在2周后上线

**Comment by xuexiaokang** [comment]
好的，辛苦了

**Comment by shc0743** [comment]
![Snipaste_2024-12-01_12-10-54](https://github.com/user-attachments/assets/621bd5c5-bdb4-4693-9227-ee60635fb3bc)
正在打包中，打包完成后直接更新即可使用

**Comment by shc0743** [comment]
批量格式化功能已完成，批量写入功能下个星期再添加

**Comment by shc0743** [comment]
关于更多批量操作相关的讨论将移至 #7 进行
